In [1]:
import pandas as pd
import numpy as np
import itertools

Read in Bakery datasets

In [29]:
bakery1000 = pd.read_csv('/Users/Dima/Desktop/CSC466/apriori/1000/1000-out1.csv',sep = '\n', header = None)
bakery1000Mtemp = bakery1000.ix[:,0].values
bakery1000M = [list(map(int, x.split(','))) for x in bakery1000Mtemp]
for x in bakery1000M:
    del x[0]

In [3]:
bakery5000 = pd.read_csv('/Users/Dima/Desktop/CSC466/apriori/5000/5000-out1.csv',sep = '\n', header = None)
bakery5000Mtemp = bakery5000.ix[:,0].values
bakery5000M = [list(map(int, x.split(','))) for x in bakery5000Mtemp]

In [52]:
bakery20000 = pd.read_csv('/Users/Dima/Desktop/CSC466/apriori/20000/20000-out1.csv',sep = '\n', header = None)
bakery20000Mtemp = bakery20000.ix[:,0].values
bakery20000M = [list(map(int, x.split(','))) for x in bakery20000Mtemp]
for x in bakery20000M:
    del x[0]

In [96]:
exampleData = pd.read_csv('/Users/Dima/Desktop/CSC466/example/out1.csv', sep = '\n', header = None)
exampleDataTemp = exampleData.ix[:,0].values
exampleDataM = [list(map(int, x.split(','))) for x in exampleDataTemp]

In [98]:
for x in exampleDataM:
    del x[0]

In [173]:
output = Apriori(exampleDataM, minSup=.1)

[ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
[ 9 22]  +  9
deleeeeted2  [ 1  9 12 14 15 16 22 36 49]
deleeeeted2 after   [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
[ 9 22]  +  22
deleeeeted2  [ 1  9 12 14 15 16 22 36 49]
deleeeeted2 after   [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
[12 16]  +  12
deleeeeted2  [ 1  9 12 14 15 16 22 36 49]
deleeeeted2 after   [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
[12 16]  +  16
deleeeeted2  [ 1  9 12 14 15 16 22 36 49]
deleeeeted2 after   [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
deleteed  [ 1  9 12 14 15 16 22 36 49]
de

In [174]:
output

[array([ 1,  9, 12, 14, 15, 16, 22, 36, 49,  1,  9, 12, 14, 15, 16, 22, 36,
        49,  1,  9, 12, 14, 15, 16, 22, 36, 49,  1,  9, 12, 14, 15, 16, 22,
        36, 49,  1,  9, 12, 14, 15, 16, 22, 36, 49,  1,  9, 12, 14, 15, 16,
        22, 36, 49]), array([[ 9, 22],
        [12, 16],
        [15, 36],
        [12, 14],
        [14, 16],
        [ 1, 49]]), array([], dtype=float64)]

In [164]:
output

[array([-1,  9, 12, 14, 15, 16, 22, 36, 49]), array([[12, 16],
        [15, 36],
        [14, 16]]), array([[12, 14, 16]])]

In [109]:
output

[[-1, -1, -1, -1, -1, -1, -1, -1, -1], array([[15, 36],
        [ 1, 49]]), [array([12, 14, 16])]]

In [91]:
output

[[36], array([[15, 36],
        [ 1, 49]]), [array([12, 14, 16])]]

In [82]:
output

[[36], array([[15, 36],
        [ 1, 49]]), [array([12, 14, 16])]]

In [64]:
output


[[36], array([[15, 36],
        [ 1, 49]]), [array([12, 14, 16])]]

In [83]:
9,22 remove 36

SyntaxError: invalid syntax (<ipython-input-83-500659672531>, line 1)

In [66]:
result = set(x for l in exampleDataM for x in l)

Start implementation of the Apriori algorithm. 

In [6]:
def support(item, baskets):
    top = sum([1 if item in basket else 0 for basket in baskets])
    bottom = len(baskets)
    return top*1.0/bottom

In [7]:
def getPairs(F, k):
    outList = list()
    for first in F:
        for second in F:
            if first.size == second.size and first.size == k:
                outList.append([first, second, np.unique(np.hstack(np.array([first,second])))])
    return outList
                

In [8]:
def checkSubset(F, check, k):
    out = False
    if k >= 2:
        for val in F:
            if np.array_equal(val,check) == True:
                out = True
    else:
        if check in F:
            out = True
    return out

This works :)

In [12]:
def candidateGen(F, k):
    C = []
    for pair in getPairs(F,k):
        if pair[2].size == pair[0].size + 1:
            c = pair[2]
            flag = True
            for s in list(itertools.combinations(c, c.size - 1)):
                if checkSubset(F,s,k) == False:
                    flag = False
            if flag == True:
                if len(set(c)) == len(c) != True:
                    C.append(list(c))
    uniqueC = [list(x) for x in set(tuple(x) for x in C)]
    arrayC = [np.array(x) for x in uniqueC]
    return arrayC

This isnt dont either.

In [172]:
def Apriori(T, minSup):
    I =  np.array(list(set(x for l in T for x in l)))
    Fk = []; Fk.append(None);
    firstIter = np.array(list(filter(lambda a: a != -1, [x if support(x, T) >= minSup else -1 for x in I])))
    print(firstIter)
    Fk.append(firstIter)
    k = 2
    while len(Fk[k-1]) != 0:
        Ck = candidateGen(Fk[k-1], k-1)
        count = {}
        for c in Ck:
            count[tuple(c)] = 0
        for t in T:
            for c in Ck:
                if set(tuple(c)) <= set(tuple(t)):
                    count[tuple(c)] += 1
        tmpFk = []
        for c in Ck:
            if count[tuple(c)]*1.0/len(T) >= minSup:
                tmpFk.append(c)
        Fk.append(np.array(tmpFk))
        for j, newTerm in enumerate(Fk[k]):
            for i, term in enumerate(Fk[k-1]):
                if k-1 == 1 and newTerm.__contains__(term):
                    print("deleteed ", Fk[k-1])
                    Fk[k-1][i] = -1
                    
                elif k-1 > 1 and  set(tuple(term)) <= set(tuple(newTerm)):
                    print(newTerm, " + ", term)
                    print("deleeeeted2 ",Fk[k-1])
                    Fk[k-1] = np.array(np.delete(Fk[k-1], i, 0))
                    print("deleeeeted2 after  ",Fk[k-1])

        k = k + 1
    Fk = Fk[1:-1]
    return Fk

In [ ]:
newterm = np.array([12,36])

In [17]:
set(tuple(np.array([12,31]))) <= set(tuple(np.array([12,31,36])))

True

In [18]:
items = list(np.arange(1,51))

In [86]:
t = Apriori(bakery1000M, .03)
t

[[6, 8, 10, 13, 17, 20, 21, 25, 26, 28, 29, 30, 34, 39, 43, 47, 49],
 array([[ 1, 19],
        [24, 41],
        [23, 24],
        [14, 44],
        [ 4,  9],
        [ 5, 22]]),
 array([[ 0,  2, 46],
        [16, 32, 45]]),
 [array([12, 31, 36, 48])]]

In [58]:
output = Apriori(bakery1000M, items, .05)

In [59]:
output

[[1,
  2,
  3,
  4,
  7,
  9,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  23,
  24,
  28,
  29,
  31,
  32,
  33,
  35,
  36,
  37,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49],
 [array([27, 28]), array([ 5, 22])]]